We are looking forward to joining you and over 100 startups, cities, and investors at Smart City Startups 2014 in Miami.
See below for more details about location, hotel, transportation, and contacts. Also included are some calender items making it easier to add the event to your calendar.

Also attached is the 'Smart City Startups Event Guide'. 

Location
========
The Light Box
404 NW 26th St.
Miami, FL 33127
P: (305) 576-4350


Hotels
======
B2 Hotel Miami Downtown 
(305) 358-4555 

Courtyard Marriott Downtown 
(305) 374-3000 

Hyatt Regency Downtown 
(305) 358-1234 
Rate: $139/night + tax
To book, call: 1-888-421-1442 and ask for the 'Smart City Startups' group rate

Marriott Biscayne Bay 
(305) 374-3900 

Omni Hilton 
(305) 374-0000 
Rate: $159/night + 13% tax
To book, call: 1-800-HILTONS and ask for the 'Smart City Startups' group rate


Transportation
==============
ZipCar 
(866) 494-7227 

Car2Go 
(877) 488-4224
Contact: Lisette Garcia
Promo Code will be provided for our guests. Reservations must be made prior to arrival. Mention Smart City Startups event.
*Mercedes Benz Corporate Run is April 24th at 645p so traffic in/out of downtown will be slow


Contacts
========
Stonly Baptiste
P: (786) 393-0998
stonly@urban.us

Shaun Abrahamson
P: (646) 258-7957
shaun@urban.us

Nina Rodriguez
P: (561) 573-9824
nadjalisse@cvoxgroup.com


Calendar Item
=============
Outlook : attached

iCal : attached

Google : https://www.google.com/calendar/render?action=TEMPLATE&text=Smart%20City%20Startups%202014&dates=20140424T120000Z/20140425T173000Z&details=smartcitystartups.com&location=404%20NW%2026th%20St.%20Miami,%20FL%2033127&pli=1&uid=&sf=true&output=xml

Yahoo : https://calendar.yahoo.com/?v=60&view=d&type=20&url=&title=Smart%20City%20Startups%202014&st=20140424T120000Z&dur=2930&desc=smartcitystartups.com&in_loc=404%20NW%2026th%20St.%20Miami,%20FL%2033127&uid=

Hotmail : https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=12&ct=1395846484&rver=6.4.6456.0&wp=MBI_SSL_SHARED&wreply=https%3a%2f%2fbay02.calendar.live.com%2fcalendar%2fcalendar.aspx%3frru%3daddevent&lc=1033&id=64362&mkt=en-us